---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-14.04
  driver:
    box: trusty64
    box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
- name: ubuntu-12.04
  driver:
    box: precise64
    box_url: http://files.vagrantup.com/precise64.box
- name: ubuntu-10.04
  driver:
    box: lucid64
    box_url: http://files.vagrantup.com/lucid64.box

suites:
  - name: default
    run_list:
      - recipe[libjpeg::default]
    attributes:
